name: build_docker

on:
  push:
    branches: [main]
  release:
    types: [created] # This will only run on new releases

jobs:
  docker_hub_description:
    name: Docker Hub description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.en.md
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_NAMESPACE }}/chatgpt-web
          # Description length should be no longer than 100 characters.
          short-description: A third-party ChatGPT Web UI page, through the official OpenAI completion API.
          readme-filepath: README.en.md
          enable-url-completion: true

  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Get version from package.json
      - name: Get Version
        id: package_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "Package version: $PACKAGE_VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-web:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-web:v${{ env.VERSION }}
            ${{ vars.DOCKERHUB_NAMESPACE }}/chatgpt-web:${{ github.ref_name }}
            ${{ vars.DOCKERHUB_NAMESPACE }}/chatgpt-web:latest
            ${{ vars.DOCKERHUB_NAMESPACE }}/chatgpt-web:v${{ env.VERSION }}
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            RELEASE_VERSION=${{ github.ref_name }}
